--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.470.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 07-12-2020 22:46:07
-- Server version: 10.4.17
-- Client version: 4.1
-- Please backup your database before running this script
--


SET NAMES 'utf8';

--
-- Set default database
--
USE quarantine;

DELIMITER $$

--
-- Create trigger `trigger1`
--
CREATE 
	DEFINER = 'root'@'localhost'
TRIGGER after_discharge
	AFTER DELETE
	ON quarantined_person
	FOR EACH ROW
BEGIN
  UPDATE allotment SET Available=1 WHERE Room_No=OLD.Room_Number;
END
$$

DELIMITER ;