--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.470.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 07-12-2020 21:10:59
-- Server version: 10.4.17
-- Client version: 4.1
-- Please backup your database before running this script
--


SET NAMES 'utf8';

--
-- Set default database
--
USE quarantine;

DELIMITER $$

CREATE DEFINER = 'root'@'localhost'
TRIGGER after_person_insertion
	AFTER INSERT
	ON quarantined_person
	FOR EACH ROW
BEGIN
   DECLARE h_no int(1);
   SELECT Hostel_No INTO h_no FROM allotment WHERE Room_No = NEW.Room_Number;
   UPDATE allotment SET  Available=0 WHERE Room_No = NEW.Room_Number;
   INSERT INTO is_assigned(Id,Hostel_No,Floor_No,Room_No) VALUES(NEW.Id,h_no,NEW.Floor_No,NEW.Room_Number);
END
$$

DELIMITER ;