--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.470.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 07-12-2020 18:09:59
-- Server version: 10.4.17
-- Client version: 4.1
-- Please backup your database before running this script
--


SET NAMES 'utf8';

--
-- Set default database
--
USE quarantine;

DELIMITER $$
CREATE DEFINER = 'root'@'localhost'
PROCEDURE allotment_initialization()
BEGIN
   DECLARE r_no int(5);
   DECLARE h_no int(1);
   DECLARE f_no int(1);
   SET r_no = 10001,h_no = 1 , f_no = 0;
   WHILE r_no<=22050 DO
       INSERT INTO is_assigned_allotment(Hostel_No,Floor_No,Room_No,Available,Id) VALUES(h_no,f_no,r_no,1,NULL);
       SET r_no = r_no+1;
       IF r_no = 10101 THEN
          SET r_no= 11001;
          SET f_no =1 ;
       ELSEIF r_no =11101 THEN
          set r_no = 12001;
          set f_no = 2;
       ELSEIF r_no = 12051 THEN
          SET r_no= 20001;
          SET h_no = 2;
          SET f_no = 0;
       ELSEIF r_no = 20101 THEN
          SET r_no = 21001;
          SET f_no = 1;
       ELSEIF r_no = 21101 THEN
          SET r_no = 22001;
          SET f_no = 2;
      END IF;
   END WHILE;
END
$$
DELIMITER ;