--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.470.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 07-12-2020 17:49:59
-- Server version: 10.4.17
-- Client version: 4.1
-- Please backup your database before running this script
--


SET NAMES 'utf8';

--
-- Set default database
--
USE quarantine;

--
-- Create table `table1`
--
   CREATE TABLE quarantined_person (Id int(4) NOT NULL AUTO_INCREMENT PRIMARY KEY, Name varchar(20), Arrival_Date DATE, Room_Number int(5), Floor_No int(1), Going_to VARCHAR(20), Coming_from VARCHAR(20), Discharged_Date DATE, Age int(2), State VARCHAR(15), District VARCHAR(15), PIN int(6), Street_No VARCHAR(20))
  ENGINE = INNODB;

  CREATE TABLE has_phone (Id int(4), Phone_number int(10),PRIMARY KEY (Id, Phone_number), FOREIGN KEY (Id) REFERENCES quarantined_person(Id) ON DELETE CASCADE);

 CREATE TABLE allotment (Hostel_No int(1), Floor_No int(1), Room_No int(5), Available tinyint(1), PRIMARY KEY (Hostel_No, Floor_No, Room_No));

 CREATE TABLE is_assigned (Id int(4), Hostel_No int(1), Floor_No int(1), Room_No int(5), FOREIGN KEY (Id) REFERENCES quarantined_person(Id) ON DELETE CASCADE,FOREIGN KEY(Hostel_No,Floor_No,Room_No) REFERENCES allotment(Hostel_No,Floor_No,Room_No) ON DELETE CASCADE);