--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.470.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 05-12-2020 21:33:38
-- Server version: 10.4.17
-- Client version: 4.1
-- Please backup your database before running this script
--


SET NAMES 'utf8';

--
-- Set default database
--
USE quarantine;

DELIMITER $$

--
-- Create trigger `trigger1`
--
CREATE 
	DEFINER = 'root'@'localhost'
TRIGGER person_insertion
	BEFORE INSERT
	ON quarantined_person
	FOR EACH ROW
BEGIN
     DECLARE r_no int(5);
   
    SET NEW.Discharged_Date = DATE_ADD(NEW.Arrival_Date,INTERVAL 14 DAY);
     IF NEW.Age<40 THEN
        SET NEW.Floor_No = 2;
     ELSEIF NEW.Age>=40 AND NEW.Age<=60 THEN
        SET NEW.Floor_No = 1;
     ELSEIF NEW.Age>60 THEN
        SET NEW.Floor_No = 0;
     END IF;
     SELECT Room_No INTO r_no FROM allotment WHERE Floor_No = NEW.Floor_No AND Available = 1 LIMIT 1;
     SET NEW.Room_Number = r_no ;
END
$$

DELIMITER ;